jobs:
  units:
    name: units (7)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        architecture: x64
        version: 1.7
    - continue-on-error: true
      run: 'java -version

        # This value is used in "-Djvm=" later

        echo "JAVA7_HOME=${JAVA_HOME}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.8
    - continue-on-error: true
      name: Build
      run: "# Leveraging surefire's jvm option, running the test on Java 7.\n# Surefire\
        \ plugin 2.22.2 is the last version for Java 7. Newer version would fail with\
        \ \n# \"UnsupportedClassVersionError: org/apache/maven/surefire/booter/ForkedBooter\"\
        \ error.\n\n# Why are these modules are skipped?\n# google-http-client-jackson2\
        \ and google-http-client-appengine do not work with Java 7\n# any more because\
        \ of Jackson and appengine library are compiled for Java 8.\n# dailymotion-simple-cmdline-sample\
        \ and google-http-client-assembly depend on\n# google-http-client-jackson2\
        \ \nmvn --batch-mode --show-version -ntp test \\\n    --projects '!google-http-client-jackson2,!google-http-client-appengine,!samples/dailymotion-simple-cmdline-sample,!google-http-client-assembly'\
        \ \\\n    -Dclirr.skip=true -Denforcer.skip=true -Dmaven.javadoc.skip=true\
        \ \\\n    -Dgcloud.download.skip=true -T 1C \\\n    -Dproject.surefire.version=2.22.2\
        \ \\\n    -Djvm=${JAVA7_HOME}/bin/java\n"
      shell: bash
name: ci-java7
on:
  repository_dispatch:
    types: trigger-ga___ci-java7.yaml
